module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/infrastructure/database/**',
    '!src/infrastructure/services/**',
    '!src/infrastructure/workers/**',
    '!src/presentation/controllers/DriverController.ts',
    '!src/presentation/controllers/PassengerController.ts',
    '!src/presentation/middlewares/**',
    '!src/presentation/routes/**',
    '!src/presentation/schemas/**',
    '!src/presentation/dtos/**',
    '!src/shared/container/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleNameMapper: {
    '^@domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@application/(.*)$': '<rootDir>/src/application/$1',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@presentation/(.*)$': '<rootDir>/src/presentation/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@mocks/(.*)$': '<rootDir>/tests/__mocks__/$1',
  },
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
